name: apiconnectapp
description: "A Flutter app to display weather and news from online APIs."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  retrofit: ^4.9.0
  provider: ^6.1.5+1
  json_annotation: ^4.9.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  retrofit_generator: ^10.0.6
  json_serializable: ^6.11.1
  mockito: ^5.5.1

flutter:
  uses-material-design: true
  assets:
    - .env
